# Site settings
title: Testing Lunr.js with Jekyll
email: info@wisdomgroup.com
description: "This is only a test. Even this extra line is a test! Why would someone choose Octopress over Jekyll, or the reverse?"
baseurl: ""
url: "http://rayhightower.com"

# Build settings
markdown: kramdown
permalink: prett

# Added by to support Lunr.js by RTH on 1/6/2015
gems: ['jekyll-lunr-js-search']


